version: 0.3.{build}-ci
pull_requests:
  do_not_increment_build_number: true
configuration: Release
shallow_clone: true
install:
- cmd: >-
    set PATH=C:\Tools\NUnit3\bin;%PATH%
skip_commits:
  message: /nobuild/
before_build:
- cmd: >-
    nuget restore src\Imgix-Dotnet.sln
    
    src\nuget\UpdateDependencyVersions.bat
build:
  verbosity: minimal
after_build:
- cmd: >-
    nuget pack src\nuget\Imgix-Dotnet.nuspec -o src\nuget -version %APPVEYOR_BUILD_VERSION%

    nuget pack src\nuget\Imgix-Dotnet.Configuration.AppConfig.nuspec -o src\nuget -version %APPVEYOR_BUILD_VERSION%
test_script:
- cmd: NUNIT3-CONSOLE %APPVEYOR_BUILD_FOLDER%\src\Imgix-Dotnet.Tests\bin\Release\Imgix-Dotnet.Tests.dll
artifacts:
- path: TestResult.xml
- path: src\nuget\Imgix-Dotnet.*.nupkg
  name: imgixDotnetPackages
deploy:
- provider: NuGet
  server: https://www.myget.org/F/imgix-dotnet-ci/api/v2/package
  api_key:
    secure: eOTUGAs/4UY79g3/H45TXRg2aUjTpLfQ6vkxjXe9n/tY0F1dkOPOYABoStu2JPz8
  skip_symbols: true
  artifact: imgixDotnetPackages
  on:
    branch: Master
on_finish:
- ps: >-
    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))
