version: 1.0.{build}-ci
pull_requests:
  do_not_increment_build_number: true
configuration: Release
shallow_clone: true
install:
- cmd: >-
    appveyor DownloadFile https://github.com/nunit/nunit/releases/download/3.0.0/NUnit-3.0.0.zip

    7z x -oC:\Tools\NUnit3 nunit-3.0.0.zip > NUL

    set PATH=C:\Tools\NUnit3\bin;%PATH%
before_build:
- cmd: nuget restore src\Imgix-LinkBuilder.sln
build:
  verbosity: minimal
after_build:
- cmd: nuget pack src\nuget\Imgix-LinkBuilder.nuspec -o src\nuget -version %APPVEYOR_BUILD_VERSION%
test_script:
- cmd: NUNIT3-CONSOLE %APPVEYOR_BUILD_FOLDER%\src\Imgix-LinkBuilder.Tests\bin\Release\Imgix-LinkBuilder.Tests.dll
artifacts:
- path: TestResult.xml
- path: src\nuget\Imgix-LinkBuilder.*.nupkg
  name: imgixLinkBuilderPackage
deploy:
- provider: NuGet
  server: https://www.myget.org/F/imgix-linkbuilder-ci/api/v2/package
  api_key:
    secure: eOTUGAs/4UY79g3/H45TXRg2aUjTpLfQ6vkxjXe9n/tY0F1dkOPOYABoStu2JPz8
  skip_symbols: true
  artifact: imgixLinkBuilderPackage
  on:
    branch: Master
on_finish:
- ps: >-
    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))